home/urls.py
from django.urls import path

from . import views

app_name="home"

urlpatterns = [
    path("", views.index, name="index"),
]

kurooms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('listings/', include('listings.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

listings/urls.py
from django.urls import path
from . import views

app_name = "listings"

urlpatterns = [
    path("index/", views.MainView.as_view(), name="all"),
    path("create/", views.PropertyCreate.as_view(), name="create"),
    path("update/<int:pk>/", views.PropertyUpdate.as_view(), name="update"),
    path("delete/<int:pk>/", views.PropertyDelete.as_view(), name="delete"),
]

home/models.py
from django.db import models

# Create your models here.

listings/models.py
from django.db import models
from django.conf import settings

class Property(models.Model):
    """blank set to true makes the corresponding form fields not required"""

    title = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)
    address = models.CharField(max_length=200, blank=True)
    contact_1 = models.CharField(max_length=10)
    contact_2 = models.CharField(max_length=10, blank=True)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title 

home/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

def index(request):
    return redirect(reverse("listings:all"))

listings/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

from django.http import HttpResponse
from .models import Property
from .owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView

class MainView(OwnerListView):
    model = Property
    fields = ["title", "address", "contact_1", "contact_2"]

class PropertyCreate(OwnerCreateView):
    model = Property
    fields = ["title", "address", "contact_1", "contact_2"]
    success_url = reverse_lazy("listings:all")

class PropertyUpdate(OwnerUpdateView):
    model = Property
    fields = ["title", "address", "contact_1", "contact_2"]
    success_url = reverse_lazy("listings:all")

class PropertyDelete(OwnerDeleteView):
    model = Property
    success_url = reverse_lazy("listings:all")

listings/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="42-42">

<meta name="dj4e-code" content="99999999">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2024-01-04">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

listings/templates/listings/property_confirm_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}

   <h1>Delete Review</h1>

   <p>Are you sure you want to delete review: {{property}}?? </p>

   <form action="", method="post">
	{% csrf_token %}
	<input type="submit" value="Yes, delete">
   </form>

{% endblock %}

listings/templates/listings/property_form.html
{% extends "base_bootstrap.html" %}
{% block content %}
<p>
  {% load crispy_forms_tags %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'listings:all' %}';return false;">
  </form>
</p>
{% endblock %}

listings/templates/listings/property_list.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Accomodations</h1>
<p>
{% if property_list %}
<ul>
  {% for property in property_list %}
    <li>

	<ul>
		<li> {{ property.title }} </li>
		<li> {{ property.address }} </li>
		<li> {{ property.contact_1 }} </li>

                <li>   {% if property.owner == user %}
                           (<a href="{% url 'listings:update' property.id %}">Edit</a> |
                           <a href="{% url 'listings:delete' property.id %}">Delete</a>)
                       {% endif %} 
                 </li>
        </ul>
        
    </li>
    <p></p>
  {% endfor %}
</ul>
{% else %}
  <p>There are no properties in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'listings:create' %}">Add an Accomodation</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'listings:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'listings:all' %}">Login</a>
{% endif %}
</p>
{% endblock %}